# Server port
server.port=9091

# Kafka Bootstrap server
spring.kafka.bootstrap-servers=localhost:9092

# Kafka order group
spring.kafka.consumer.group-id=order-group

# Kafka offset
spring.kafka.consumer.auto-offset-reset=latest

# Kafka producer
spring.kafka.producer.send.log.topic=payment_success